name: prettier
on: [pull_request]
jobs:
  prettier:
    name: runner / prettier
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v4
      - run: |
          npm install
          npm run format
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply Prettier Change
