name: Formatter
on: [pull_request]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/*.{ts,tsx,js,jsx,json}
        id: get-diff

      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'

      - name: Run Prettier
        run: |
          npm ci
          npx prettier --write $(echo "${{ steps.get-diff.outputs.files }}" | tr '\n' ' ')
        env:
          GIT_DIFF_FILTERED: ${{ steps.get-diff.outputs.files }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Prettier Change
          add: 'true'
          branch: ${{ github.head_ref }}